### PR TITLE
Move spacing to a more consistent number

### PR DESCRIPTION
**Pull request by SaraVieira**
This is a general design PR.

- Styles were moved to tailwind and added that compilation step
- all spacing is matching tailwind specs
- same for font size
- makes axo team the default theme

### CODE REVIEW

**Comment by sarahghp** [comment]
@SaraVieira, I'll take a deeper look, but I did want to mention that when I suggested we move to Tailwind for this, I meant not just using `@apply` but applying the utility approach more generally. The reason for this is that if we are generating static sites for folks, making small tweaks rely on deleting one class as applied to one element rather than digging into nested CSS would be helpful, especially if we expect these folks to be of the non-frontend variety. 

If the parser won't let us inject the classes, we could also possibly use [@layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) and create them a user layer that will override without nesting?

I also wonder if moving this to the turborepo apps would allow you to import the CSS directly from the Fringe? That way, we wouldn't have to worry about keeping text styles in sync as we iterate going forward. Anyways, comment with more details coming soon!

**Comment by SaraVieira** [comment]
When you add any sort of styles i append the ID so that people don't have to worry about speceficity in general and it will always work for them as i think that's a better experience in general 

About moving it i don't think that's a good idea since this will be converted to rust and the other repo is also not open source. This node version is temporary

**Comment by SaraVieira** [comment]
To change styles you don't get our styles btw, you create your own css file or override it in JSON and these two versions beat our styles in terms of specificity

**Comment by sarahghp** [comment]
Design thoughts in no specific order:

* I would make the links next to headers only show on hover — with links, plus emoji in one case, it gets pretty noisy.

* These backgrounds should be the same color or different colors along the same spectrum. Mixing warm and cold doesn't look quite right. (I would say it should be cool because the Axo grays are on the cool spectrum.)

Screen Shot 2022-10-03 at 2 59 05 PM

* I recommend adding a `margin-top` to the headers so there is a space between the end of one section and the start of the next. When they run into one another it doesn't give youe eye a place to rest.

* The font-size is a bit large for reading. Dropping to 16 or 18 would be a bit more legible. (16 is nice becuase it's `1rem`, so then `rem`-based spacing is in harmony, but some of that's just feel.

* I would constrain the width of the text blocks. In general, the ideal line length is 45 to 75 characters, although, I think the top end could be pushed slightly.

* I really like making the `code` callouts in text a different color, but that is the most aesthetic comment here.

* In the table should we put the filenames in `code` monospace?

* The `deployment` link currently doesn't work.

**Comment by sarahghp** [comment]
> About moving it i don't think that's a good idea since this will be converted to rust and the other repo is also not open source. This node version is temporary

Okay, seems reasonable. I would recommend we do that with the Rust version then, and if we open-source things, it might be worthwhile to consider making an open-source Fringe package so we can pull from the same place, just to save lots of manually keeping things in sync. Or to even publish just the Fringe stylesheet somewhere so we can load it remotely like you do with normalize.

> When you add any sort of styles i append the ID so that people don't have to worry about speceficity in general and it will always work for them as i think that's a better experience in general

That's still making a specificity war, isn't it? Is there a reason not to use `@layer`, now that it exists? Then we don't have to intervene and append any IDs, but can list the layer oders. It seems like that's more working with the grain of the modern web API, and then users could do things like generate their webpage without needing our system to override the styles but could, if, for instance, they were enmeshing this in a larger system.

> To change styles you don't get our styles btw, you create your own css file or override it in JSON and these two versions beat our styles in terms of specificity

I just want to check; if people give us _any_ styles do we then expect them to give us all styles? Or you are saying that we are just adding the ID to override? I assume the latter, but I just wanted to check. :)

Anyways, I hope it doesn't seem like I'm picking on you here — this is a big project and this is just a small part of it. I just want to be sure we are making the best experience we can, so I am trying to think it all through, and here seems fine enough, especially since it is temporary, so then we'll be better aligned on where we are going once we get to Rust.

**Comment by SaraVieira** [comment]
👋 

About your design suggestions:

* The links its a great idea to make only on hover and done!
* I do agree on the colors there, any idea on a color that would look better on the table?
* Added a margin top of 16px, good catch!
* I did think there was something weird with the font size, changed it to 16px
* Moved the width of the container to 1000px maximuj instead of 1100, it's a littel over the limit still but let me know how you feel and if it's more readable
* About the code callouts in text, do you think the color I am using for the blocks would be a good idea for the bg of those or maybe just a transparent black?
* Updated the table
* Fixed the deployment but in the `oranda.config.json` there is a `pathPrefix` you need to remove locally since it's there to work on gh pages

Will see the other comments tomorrow

Thank you for the design feedback!

**Pull request merged**
